# Generated by Django 5.2.8 on 2025-11-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0002_alter_wishlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlistitem",
            name="priority",
            field=models.CharField(
                choices=[
                    ("5", "Very High"),
                    ("4", "High"),
                    ("3", "Medium"),
                    ("2", "Low"),
                    ("1", "Very Low"),
                ],
                default="3",
                max_length=1,
            ),
        ),
    ]
